apiVersion: v1
kind: Service
metadata:
  name: practica2-api
  namespace: practica2
spec:
  type: NodePort
  selector:
    app: practica2-api
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080
